# Generated by Django 5.0 on 2024-09-04 13:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userkyc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userkyc',
            name='aadhar_card_image',
        ),
        migrations.RemoveField(
            model_name='userkyc',
            name='pan_card_image',
        ),
        migrations.AddField(
            model_name='userkyc',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userkyc',
            name='otp_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userkyc',
            name='aadhar_card_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(12), django.core.validators.MaxLengthValidator(12), django.core.validators.RegexValidator('^\\d{12}$', 'Aadhaar number must be exactly 12 digits.')]),
        ),
    ]
